# Generated by Django 3.1.3 on 2020-11-15 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=100)),
                ('matric_no', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=7)),
                ('level', models.CharField(default='HND II', max_length=10)),
                ('department', models.CharField(choices=[('Pharmaceutical Technology', 'Pharmaceutical Technology'), ('Computer Science', 'Computer Science'), ('Statistics and Mathematics', 'Statistics and Mathematics'), ('Microbiology', 'Microbiology'), ('Food Technology', 'Food Technology'), ('Mass Communication', 'Mass Communication'), ('Urban & Regional Planning', 'Urban & Regional Planning'), ('Civil Engineering', 'Civil Engineering'), ('Business Administration', 'Business Administration'), ('Marketing', 'Marketing'), ('Accountancy', 'Accountancy')], default='Computer Science', max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Mr', 'Mr')], max_length=5)),
                ('staff_id', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_hod', models.BooleanField(default=False)),
                ('is_schoolooficer', models.BooleanField(default=False)),
                ('is_library', models.BooleanField(default=False)),
                ('is_busary', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClearanceApp.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sundry_receipt', models.FileField(upload_to='sundry')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClearanceApp.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
