# Generated by Django 3.1.3 on 2020-11-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='is_schoolooficer',
            new_name='is_school',
        ),
    ]
