# Generated by Django 3.1.3 on 2020-11-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0003_feedback_is_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='office',
            field=models.CharField(choices=[('HOD', 'HOD'), ('SCHOOL OFFICER', 'SCHOOL OFFICER'), ('LIBRARY', 'LIBRARY'), ('BUSARY', 'BUSARY')], default='HOD', max_length=30),
            preserve_default=False,
        ),
    ]
