# Generated by Django 3.1.3 on 2020-11-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0005_remove_staff_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default='XT24YUAOQ1', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
