# Generated by Django 3.1.3 on 2020-11-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0007_auto_20201120_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
