# Generated by Django 3.1.3 on 2020-11-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0009_auto_20201120_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearance',
            name='student',
        ),
    ]
