# Generated by Django 3.1.3 on 2020-11-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0011_clearance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
