# Generated by Django 3.1.3 on 2020-11-23 13:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0012_clearance_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearance',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='clearance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='clearance',
            name='sundry_receipt',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_busary',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_hod',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_library',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_school',
        ),
        migrations.AddField(
            model_name='clearance',
            name='date_signed',
            field=models.DateField(default='2020-11-23'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clearance',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ClearanceApp.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=20)),
                ('matric_no', models.CharField(max_length=20, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('other_names', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=7)),
                ('level', models.CharField(max_length=10)),
                ('department', models.CharField(choices=[('Pharmaceutical Technology', 'Pharmaceutical Technology'), ('Computer Science', 'Computer Science'), ('Statistics and Mathematics', 'Statistics and Mathematics'), ('Microbiology', 'Microbiology'), ('Food Technology', 'Food Technology'), ('Mass Communication', 'Mass Communication'), ('Urban & Regional Planning', 'Urban & Regional Planning'), ('Civil Engineering', 'Civil Engineering'), ('Business Administration', 'Business Administration'), ('Marketing', 'Marketing'), ('Accountancy', 'Accountancy')], max_length=50)),
                ('date_signed', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClearanceApp.staff')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=20)),
                ('matric_no', models.CharField(max_length=20, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('other_names', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=7)),
                ('level', models.CharField(max_length=10)),
                ('department', models.CharField(choices=[('Pharmaceutical Technology', 'Pharmaceutical Technology'), ('Computer Science', 'Computer Science'), ('Statistics and Mathematics', 'Statistics and Mathematics'), ('Microbiology', 'Microbiology'), ('Food Technology', 'Food Technology'), ('Mass Communication', 'Mass Communication'), ('Urban & Regional Planning', 'Urban & Regional Planning'), ('Civil Engineering', 'Civil Engineering'), ('Business Administration', 'Business Administration'), ('Marketing', 'Marketing'), ('Accountancy', 'Accountancy')], max_length=50)),
                ('date_signed', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClearanceApp.staff')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(max_length=20, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=7)),
                ('level', models.CharField(max_length=10)),
                ('department', models.CharField(choices=[('Pharmaceutical Technology', 'Pharmaceutical Technology'), ('Computer Science', 'Computer Science'), ('Statistics and Mathematics', 'Statistics and Mathematics'), ('Microbiology', 'Microbiology'), ('Food Technology', 'Food Technology'), ('Mass Communication', 'Mass Communication'), ('Urban & Regional Planning', 'Urban & Regional Planning'), ('Civil Engineering', 'Civil Engineering'), ('Business Administration', 'Business Administration'), ('Marketing', 'Marketing'), ('Accountancy', 'Accountancy')], max_length=50)),
                ('sundry_receipt', models.FileField(upload_to='sundry')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClearanceApp.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Busary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=20)),
                ('matric_no', models.CharField(max_length=20, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=7)),
                ('level', models.CharField(max_length=10)),
                ('department', models.CharField(choices=[('Pharmaceutical Technology', 'Pharmaceutical Technology'), ('Computer Science', 'Computer Science'), ('Statistics and Mathematics', 'Statistics and Mathematics'), ('Microbiology', 'Microbiology'), ('Food Technology', 'Food Technology'), ('Mass Communication', 'Mass Communication'), ('Urban & Regional Planning', 'Urban & Regional Planning'), ('Civil Engineering', 'Civil Engineering'), ('Business Administration', 'Business Administration'), ('Marketing', 'Marketing'), ('Accountancy', 'Accountancy')], max_length=50)),
                ('date_signed', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClearanceApp.staff')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
