# Generated by Django 3.1.3 on 2020-11-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0013_auto_20201123_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busary',
            old_name='status',
            new_name='is_accessed',
        ),
        migrations.RenameField(
            model_name='hod',
            old_name='status',
            new_name='is_accessed',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='status',
            new_name='is_accessed',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='status',
            new_name='is_accessed',
        ),
    ]
