# Generated by Django 3.1.3 on 2020-11-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0014_auto_20201123_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='date_signed',
            field=models.DateTimeField(),
        ),
    ]
