# Generated by Django 3.1.3 on 2020-11-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0015_auto_20201123_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busary',
            name='date_signed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='library',
            name='date_signed',
            field=models.DateTimeField(),
        ),
    ]
