# Generated by Django 3.1.3 on 2020-11-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0017_busary_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearance',
            name='student',
        ),
        migrations.AddField(
            model_name='clearance',
            name='hod',
            field=models.CharField(default='omoyin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clearance',
            name='library',
            field=models.CharField(default='seun', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clearance',
            name='school_officer',
            field=models.CharField(default='oyelowo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearance',
            name='date_signed',
            field=models.DateTimeField(),
        ),
    ]
