# Generated by Django 3.1.3 on 2020-11-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0018_auto_20201124_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='signature',
            field=models.CharField(default='tola', max_length=20),
            preserve_default=False,
        ),
    ]
