# Generated by Django 3.1.3 on 2020-11-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0019_clearance_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='is_accessed',
            field=models.BooleanField(default=False),
        ),
    ]
