# Generated by Django 3.1.3 on 2020-11-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0020_clearance_is_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
