# Generated by Django 3.1.3 on 2020-11-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0021_feedback_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.CharField(max_length=50),
        ),
    ]
