# Generated by Django 3.1.3 on 2020-11-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0022_auto_20201125_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='slug',
        ),
    ]
