# Generated by Django 3.1.3 on 2020-11-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0025_auto_20201125_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='staff',
            new_name='user',
        ),
    ]
