# Generated by Django 3.1.3 on 2020-11-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0026_auto_20201125_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='staff',
        ),
    ]
