# Generated by Django 3.1.3 on 2020-11-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0027_auto_20201125_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='department',
            field=models.CharField(default='Computer Science', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='matric_no',
            field=models.CharField(default='14/69/0109', max_length=20),
            preserve_default=False,
        ),
    ]
