# Generated by Django 3.1.3 on 2020-11-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearanceApp', '0028_auto_20201126_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='hod_email',
            field=models.EmailField(default='samuelomoyin@gmai.com', max_length=254),
            preserve_default=False,
        ),
    ]
